DATASET="../dataset"
INT_RANDOM_SEED = 42
MUSIC_SAMPLE_RATE = 16000
# MUSIC_SAMPLE_RATE = 16000
STR_CH_FIRST = 'channels_first'
STR_CH_LAST = 'channels_last'
DATA_LENGTH = MUSIC_SAMPLE_RATE * 10
INPUT_LENGTH = MUSIC_SAMPLE_RATE * 10
CHUNK_SIZE = 16

FMA_TAG_INFO = {
    '20th century classical': "genre",
    'abstract hip-hop': "genre",
    'african': "location",
    'afrobeat': "genre",
    'alternative hip-hop': "style",
    'ambient': "style",
    'ambient electronic': "style",
    'americana': "location",
    'asia-far east': "location",
    'audio collage': "genre",
    'avant-garde': "style",
    'balkan': "location",
    'banter': "style",
    'big band/swing': "style",
    'bigbeat':"style",
    'black-metal':"style",
    'bluegrass':"location",
    'blues':"genre",
    'brazilian':"location",
    'breakbeat':"style",
    'breakcore - hard':"style",
    'british folk':"style",
    'celtic':"style",
    'chamber music':"style",
    'chill-out':"mood",
    'chip music':"style",
    'chiptune':"instrument",
    'choral music':"style",
    'christmas':"theme",
    'classical':"genre",
    'comedy':"genre",
    'compilation':"style",
    'composed music':"style",
    'contemporary classical':"style",
    'country':"genre",
    'country & western':"genre",
    'cumbia':"location",
    'dance':"theme",
    'death-metal':"style",
    'deep funk':"style",
    'disco':"genre",
    'downtempo':"style",
    'drone':"style",
    'drum & bass':"instrument",
    'dubstep':"style",
    'easy listening':"mood",
    'easy listening: vocal':"instrument",
    'electro-punk':"style",
    'electroacoustic':"style",
    'electronic':"genre",
    'europe':"location",
    'experimental':"genre",
    'experimental pop':"style",
    'fado': "location",
    'field recordings':"style",
    'flamenco':"location",
    'folk':"genre",
    'freak-folk':"style",
    'free-folk':"style",
    'free-jazz':"style",
    'french':"language",
    'funk':"genre",
    'garage':"style",
    'glitch':"style",
    'gospel':"style",
    'goth':"style",
    'grindcore':"style",
    'hardcore':"style",
    'hip-hop':"genre",
    'hip-hop beats':"style",
    'holiday':"theme",
    'house':"genre",
    'idm':"style",
    'improv':"style",
    'indian':"location",
    'indie-rock':"style",
    'industrial':"style",
    'instrumental':"genre",
    'international':"style",
    'interview':"theme",
    'jazz':"genre",
    'jazz: out': "style",
    'jazz: vocal': "style",
    'jungle': "style",
    'kid-friendly': "style",
    'klezmer': "location",
    'krautrock':"style",
    'latin':"location",
    'latin america':"location",
    'lo-fi':"genre",
    'loud-rock':"style",
    'lounge':"theme",
    'metal':"genre",
    'middle east':"location",
    'minimal electronic':"style",
    'minimalism':"style",
    'modern jazz':"style",
    'musical theater':"theme",
    'musique concrete':"theme",
    'n. indian traditional':"location",
    'nerdcore':"style",
    'new age':"genre",
    'new wave':"style",
    'no wave':"style",
    'noise':"style",
    'noise-rock':"style",
    'north african':"style",
    'novelty':"style",
    'nu-jazz':"style",
    'old-time / historic':"style",
    'opera':"style",
    'pacific':"location",
    'poetry':"style",
    'polka':"style",
    'pop':"genre",
    'post-punk':"style",
    'post-rock':"style",
    'power-pop':"style",
    'progressive':"style",
    'psych-folk':"style",
    'psych-rock':"style",
    'punk':"genre",
    'radio':"theme",
    'radio art':"theme",
    'radio theater':"theme",
    'rap':"genre",
    'reggae - dancehall':"style",
    'reggae - dub':"style",
    'rock':"genre",
    'rock opera':"style",
    'rockabilly':"mood",
    'romany (gypsy)':"style",
    'salsa':"style",
    'shoegaze':"style",
    'singer-songwriter':"style",
    'skweee':"style",
    'sludge':"style",
    'soul-rnb':"style",
    'sound art':"style",
    'sound collage':"style",
    'sound effects':"style",
    'sound poetry':"style",
    'soundtrack':"genre",
    'south indian traditional':"location",
    'space-rock':"style",
    'spanish':"language",
    'spoken':"style",
    'spoken weird':"style",
    'spoken word':"style",
    'surf':"style",
    'symphony':"style",
    'synth pop':"style",
    'talk radio':"style",
    'tango':"style",
    'techno':"style",
    'thrash':"style",
    'trip-hop':"style",
    'turkish':"location",
    'unclassifiable':"theme",
    'western swing':"location",
    'wonky':"style"
}